# Generated by Django 2.2.7 on 2020-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=64, verbose_name='productname')),
                ('productdesc', models.CharField(max_length=200, verbose_name='productdesc')),
                ('producter', models.CharField(max_length=200, verbose_name='producter')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create_time')),
            ],
        ),
    ]
